select c.TITLE,c.BOARD_ID,r.REPLY_ID,r.WRITER_ID,r.CONTENTS,
       DATE_FORMAT(r.CREATED_DATE, '%Y-%M-%D') as CREATED_DATE
from USED_GOODS_BOARD as c join USED_GOODS_REPLY as r on r.BOARD_ID = c.BOARD_ID
where DATE_FORMAT(c.CREATED_DATE,'%Y-%M') = 2022-10
order by r.CREATED_DATE, c.TITLE;